#!/usr/bin/env bash

# ==== CHECK THAT GO SOURCE FILES ARE FORMATTED ====
# Code from https://github.com/dnephin/pre-commit-golang
# Capture and print stdout, since gofmt doesn't use proper exit codes
gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$')
[ -z "$gofiles" ] && exit 0

unformatted=$(gofmt -l $gofiles)
[ -z "$unformatted" ] && exit 0

# Some files are not gofmt'd. Print message and fail.

echo >&2 "Go files must be formatted with gofmt. Please run:"
for fn in $unformatted; do
    echo >&2 "  gofmt -w $PWD/$fn"
done

exit 1
